// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jojfdyuenghlpswudyvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvamZkeXVlbmdobHBzd3VkeXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjc5NjcsImV4cCI6MjA2MjY0Mzk2N30.z2Ee89ihqIvS6A7O0Gr3P5u4ZuSGJDZ21PNlMy9cO-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);